version: '3'

volumes:
  database_data:
    driver: local

services:
  nginx:
    image: nginx:latest
    restart: "no"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/sites.template:/etc/nginx/sites-available/sites.template
      - ./nginx/default/html:/var/www/html
      - ./nginx/log/nginx:/var/log/nginx
      - ./nginx/letsencrypt/:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOSTNAME=${HOST_NAME:-sl}.${DOMAIN_SUB:-lab}.${DOMAIN_ROOT:-bigbluebutton.org}
    depends_on:
      - scalelite.api
    command: /bin/bash -c "envsubst '$$NGINX_HOSTNAME' < /etc/nginx/sites-available/sites.template > /etc/nginx/sites-enabled/sites.conf && exec nginx -g 'daemon off;'"

  redis:
    image: redis
    restart: "no"
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ./data/redis/:/data

  postgres:
    image: postgres:9.5
    restart: "no"
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    environment:
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=password

  scalelite.api:
    entrypoint: [bin/start]
    image: blindsidenetwks/scalelite:master
    restart: "no"
    ports:
      - 127.0.0.1:3000:3000
    links:
      - redis
      - postgres
    volumes:
      - ./scalelite/log/api:/srv/scalelite/log
      - ./scalelite/bin/start:/srv/scalelite/bin/start
      - ./scalelite/config/database.yml:/srv/scalelite/config/database.yml
      - ./scalelite/tmp/pids/:/usr/src/app/tmp/pids
      - ./scalelite/tmp/sockets/:/usr/src/app/tmp/sockets
      - ./scalelite/tmp/cache/assets:/usr/src/app/tmp/cache/assets
    env_file: ./scalelite/.env
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_HOST=postgres
      - DB_NAME=scalelite_production
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - URL_HOST=${HOST_NAME:-sl}.${DOMAIN_SUB:-lab}.${DOMAIN_ROOT:-bigbluebutton.org}

  scalelite.poller:
    entrypoint: [bin/start-poller]
    image: blindsidenetwks/scalelite:master
    restart: "no"
    ports:
      - 127.0.0.1:3001:3000
    links:
      - redis
    volumes:
      - ./scalelite/log/poller:/srv/scalelite/log
      - ./scalelite/bin/start-poller:/srv/scalelite/bin/start-poller
    env_file: ./scalelite/.env
    environment:
      - REDIS_URL=redis://redis:6379
      - URL_HOST=${HOST_NAME:-sl}.${DOMAIN_SUB:-lab}.${DOMAIN_ROOT:-bigbluebutton.org}
      - INTERVAL=60
